micronaut:
  application:
    name: vehicle-status-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

insurance:
  base-url: https://insurance.com
  retry:
    max-attempts: 3
    delay-in-millis: 2000

maintenance:
  base-url: https://topgarage.com
  retry:
    max-attempts: 3
    delay-in-millis: 2000

